openapi: 3.0.3
info:
  title: Mini E-Commerce API
  description: Mini E-Commerce API
  version: 1.0.0
servers:
  - url: 'http://localhost:5000/api/v1'
paths:
  /authentication/register:
    "post":
      tags:
        - Authentication API
      description: "Authentication Register"
      summary: "Authentication Register"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: "User Successfully Register"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/AuthenticationResponse"
        '400':
          description: "Missing Validation Authentication Register"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        items:
                          type: string
                      email:
                        type: array
                        items:
                          type: string
                      password:
                        type: array
                        items:
                          type: string
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorResponse"
  /authentication/login:
    post:
      tags:
        - Authentication API
      description: "Authentication Login"
      summary: "Authentication Login"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: "User Successfully Login"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/AuthenticationResponse"
        '400':
          description: "Missing Validation Authentication Login"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        items:
                          type: string
                      password:
                        type: array
                        items:
                          type: string
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorResponse"
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorResponse"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ServerErrorResponse:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        message:
          type: string
    AuthenticationResponse:
      type: object
      properties:
        user_id:
          type: string
        token:
          type: string
        expires_in:
          type: number